name: Project CI

on:
  push:
    branches:
     - main

jobs:
  project-test:
    runs-on:  ubuntu-latest

    steps:
      # Check out the Repository and its changes
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Python version 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # Install Required Libraries
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./project/requirements.txt

      # Run the tests.py using tests.sh
      - name: Run Test
        id: project_test
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
